backend/core/urls.py
from django.urls import path

from backend.core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

backend/expense/urls.py
from django.urls import path

from backend.expense import views as v

app_name = 'expense'


urlpatterns = [
    path('', v.ExpenseListView.as_view(), name='expense_list'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('expense/', include('backend.expense.urls', namespace='expense')),
    path('admin/', admin.site.urls),
]

backend/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

backend/expense/models.py
from django.db import models

from backend.core.models import TimeStampedModel


class Expense(TimeStampedModel):
    description = models.CharField('descrição', max_length=50)
    payment_date = models.DateField('data de pagamento', null=True, blank=True)
    value = models.DecimalField('valor', max_digits=7, decimal_places=2)
    paid = models.BooleanField('pago', default=False)

    class Meta:
        ordering = ('id',)
        verbose_name = 'despesa'
        verbose_name_plural = 'despesas'

    def __str__(self):
        return self.description

backend/core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)

backend/expense/views.py
from django.db.models import Q
from django.views.generic import ListView

from .models import Expense


class DatatablesMixin:
    paginate = 10
    rows_per_pages = (5, 10, 20, 50, 100)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rows_per_pages'] = self.rows_per_pages

        # Busca
        search = self.request.GET.get('search')
        if search:
            context['search'] = search

        # Ordenação
        sort_by = self.request.GET.get('sort_by')
        if sort_by:
            if '-' in sort_by:
                _sort_by = sort_by.replace('-', '')
                # key é o nome do campo a ser ordenado.
                key = _sort_by
            else:
                # Muda a ordenação (como se fosse toggle).
                _sort_by = f'-{sort_by}'
                key = sort_by
        else:
            # Pega o nome do primeiro campo de ordenação do model.
            key = self.model._meta.ordering[0].replace('-', '')
            _sort_by = key

        # Atualiza o dicionário procurando pelo campo de ordenação.
        self.sort_by[key]['ordering'] = _sort_by
        context['sort_by'] = self.sort_by
        context['ordering'] = _sort_by

        # Linhas por página
        rows_per_page = self.request.GET.get('rows_per_page')
        if rows_per_page:
            context['rows_per_page'] = rows_per_page
        else:
            context['rows_per_page'] = self.paginate

        # Total de itens
        total_items = self.model.objects.values_list('id', flat=True).count()
        context['total_items'] = total_items

        return context

    def get_paginate_by(self, queryset):
        rows_per_page = self.request.GET.get('rows_per_page')
        if rows_per_page:
            return rows_per_page
        return self.paginate


class ExpenseSearchMixin:
    '''
    Campo de busca
    '''

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get('search')

        if search:
            return queryset.filter(
                Q(description__icontains=search)
            )
        return queryset


class ExpenseSortMixin:
    '''
    Ordenação
    '''

    def __init__(self):
        self.sort_by = {
            'id': {
                'label': self.model.id.field.verbose_name.capitalize(),
                'ordering': self.model.id.field.name,
            },
            'description': {
                'label': self.model.description.field.verbose_name.capitalize(),
                'ordering': self.model.description.field.name,
            },
            'payment_date': {
                'label': self.model.payment_date.field.verbose_name.capitalize(),
                'ordering': self.model.payment_date.field.name,
            },
            'value': {
                'label': self.model.value.field.verbose_name.capitalize(),
                'ordering': self.model.value.field.name,
            },
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sort_by'] = self.sort_by
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        sort_by = self.request.GET.get('sort_by')

        if sort_by:
            return queryset.order_by(sort_by)
        return queryset


class ExpenseListView(DatatablesMixin, ExpenseSearchMixin, ExpenseSortMixin, ListView):
    model = Expense
    template_name = 'expense/expense_list.html'

backend/core/templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <title>Django</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.6.1"></script>

    {% block css %}{% endblock css %}

  </head>

  <body>
    <div class="container">
      {% include "includes/nav.html" %}
      {% block content %}{% endblock content %}
    </div>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    {% block js %}{% endblock js %}
  </body>

</html>

backend/core/templates/includes/nav.html
<!-- includes/nav.html -->
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'core:index' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'expense:expense_list' %}">Despesas</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        {% if request.user.is_authenticated %}
          <a class="nav-link">Olá {{ request.user.get_full_name }}</a>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>

backend/core/templates/includes/pagination.html
<!-- pagination.html -->
{% load url_replace %}
<!-- https://gist.github.com/rg3915/01ca76f099f431c24bc0536bef83076b -->
<!-- Use https://gist.github.com/rg3915/01ca76f099f431c24bc0536bef83076b#file-pagination02-html -->
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            hx-get="{% url 'expense:expense_list' %}?{% url_replace page=page_obj.previous_page_number rows_per_page=request.GET.rows_per_page search=request.GET.search %}"
            hx-target="#example"
          >&laquo;</a>
        </li>
      {% endif %}

      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 2 primeiras e 2 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' %}

          {% if page_obj.number == pg %}
            <li class="page-item active">
              <a
                class="page-link"
                hx-get="{% url 'expense:expense_list' %}?{% url_replace page=pg rows_per_page=request.GET.rows_per_page search=request.GET.search %}"
                hx-target="#example"
              >{{ pg }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a
                class="page-link"
                hx-get="{% url 'expense:expense_list' %}?{% url_replace page=pg rows_per_page=request.GET.rows_per_page search=request.GET.search %}"
                hx-target="#example"
              >{{ pg }}</a>
            </li>
          {% endif %}

        {% else %}

          {% if page_obj.number == pg %}
            <li class="page-item active">
              <a
                class="page-link"
                hx-get="{% url 'expense:expense_list' %}?{% url_replace page=pg rows_per_page=request.GET.rows_per_page search=request.GET.search %}"
                hx-target="#example"
              >{{ pg }}</a>
            </li>
          {% elif pg > page_obj.number|add:'-3' and pg < page_obj.number|add:'3' %}
            <!-- Mostra 2 páginas antes e 2 páginas depois da atual -->
            <li class="page-item">
              <a
                class="page-link"
                hx-get="{% url 'expense:expense_list' %}?{% url_replace page=pg rows_per_page=request.GET.rows_per_page search=request.GET.search %}"
                hx-target="#example"
              >{{ pg }}</a>
            </li>
          {% elif pg == page_obj.number|add:'-3' or pg == page_obj.number|add:'3' %}
            <li class="page-item">
              <a
                class="page-link"
                href=""
              >...</a>
            </li>
          {% endif %}

        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            hx-get="{% url 'expense:expense_list' %}?{% url_replace page=page_obj.next_page_number rows_per_page=request.GET.rows_per_page search=request.GET.search %}"
            hx-target="#example"
          >&raquo;</a>
        </li>
      {% endif %}

    </ul>
  </div>
</div>

backend/core/templates/index.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <h1>Django datatables htmx</h1>
    <p>Exemplo de datatables feito apenas com htmx.</p>
    <p>Veja no <a href="https://github.com/rg3915/django-datatables-htmx" target="_blank">Github</a>.</p>
  </div>
{% endblock content %}

backend/expense/templates/expense/expense_content.html
<!-- expense_content.html -->
<tr>
  <td>{{ object.id }}</td>
  <td>{{ object.description }}</td>
  <td>{{ object.value }}</td>
  <td>{{ object.payment_date|date:'d/m/Y'|default:'---' }}</td>
</tr>

backend/expense/templates/expense/expense_list.html
<!-- expense_list.html -->
{% extends "base.html" %}
{% load rows_tags %}
{% load url_replace %}

{% block content %}

  <div id="example">
    <div class="dt-panel">
      <div class="dt-left-panel">
        <select
          id="id_rows_per_page"
          name="rows_per_page"
          class="form-control"
          data-row="{{ rows_per_page }}"
          hx-get="{% url 'expense:expense_list' %}?{% url_replace rows_per_page=request.GET.rows_per_page search=request.GET.search %}"
          hx-target="#example"
        >
          {% for row in rows_per_pages %}
            <!-- Seleciona o item conforme a quantidade de linhas na página. -->
            <option
              value="{{ row }}"
              {% if row == rows_per_page %}
              selected
              {% endif %}
            >
              {{ row }}
            </option>
          {% endfor %}
        </select>
        <span class="text-muted"><small>Linhas por página</small></span>
      </div>

      <div class="dt-right-panel">
        <div class="form-inline justify-content-end">
          <input
            name="search"
            class="form-control"
            type="text"
            placeholder="Busca..."
            hx-get="{% url 'expense:expense_list' %}?{% url_replace rows_per_page=request.GET.rows_per_page search=request.GET.search %}"
            hx-target="#example"
            value="{{ request.GET.search }}"
          >
          <a
            class="btn btn-link"
            href="."
          >Limpar</a>
        </div>
      </div>
    </div>

    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>
            {% include "../includes/ordering_field.html" with url='/expense/' field=sort_by.description target='#example' %}
            {% include "../includes/ordering_icon.html" with order=sort_by.description.ordering %}
          </th>
          <th>
            {% include "../includes/ordering_field.html" with url='/expense/' field=sort_by.value target='#example' %}
            {% include "../includes/ordering_icon.html" with order=sort_by.value.ordering %}
          </th>
          <th>
            {% include "../includes/ordering_field.html" with url='/expense/' field=sort_by.payment_date target='#example' %}
            {% include "../includes/ordering_icon.html" with order=sort_by.payment_date.ordering %}
          </th>
        </tr>
      </thead>
      <tbody id="tBody">
        {% include "./expense_table.html" %}
      </tbody>
    </table>

    <div class="dt-panel">
      <div class="dt-left-panel dt-total-panel">
        <!-- Linhas 1 a 10 de 100 -->
        <!-- Linhas 11 a 20 de 100 -->
        Linhas {% first_line_count rows_per_page=rows_per_page pg_number=page_obj.number %}
        a {% last_line_count rows_per_page=rows_per_page pg_number=page_obj.number total_items=total_items %}
        de {{ page_obj.paginator.count }}
      </div>

      <div class="dt-right-panel">
        <div class="dt-pagination">
          {% include "includes/pagination.html" %}
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block js %}

  <script>
    htmx.on("htmx:afterSwap", function(evt) {
      const item = document.querySelector('#id_rows_per_page')
      item.value = item.dataset.row
    })
  </script>

{% endblock js %}

backend/expense/templates/expense/expense_table.html
<!-- expense_table.html -->
{% for object in object_list %}
  {% include "./expense_content.html" %}
{% endfor %}

backend/expense/templates/includes/ordering_field.html
{% load url_replace %}

<span
  class="span-is-link link"
  hx-get="{{url}}?{% url_replace rows_per_page=request.GET.rows_per_page search=request.GET.search sort_by=field.ordering %}"
  hx-target="{{target}}"
>
  {{ field.label }}
</span>

backend/expense/templates/includes/ordering_icon.html
<span class="float-right">
  {% if order == ordering %}
    {% if '-' in order %}
      <i class="fa fa-sort-up"></i>
    {% else %}
      <i class="fa fa-sort-down"></i>
    {% endif %}
  {% else %}
    <i class="fa fa-sort"></i>
  {% endif %}
</span>